source 'https://rubygems.org'

gem 'watir'
gem 'watir-webdriver'
gem 'rake'
gem 'rubyXL'
gem 'headless'
gem 'pry'
gem 'pry-byebug'
gem 'ocra'
gem 'dotenv'
gem 'digitalocean'
gem 'washbullet', '>= 0.4.0'
gem 'awesome_print'
gem 'facter'
gem 'colorize'
gem 'sinatra'
gem 'haml'
gem 'sass'
